// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yefuwtjterjsmykszryg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZnV3dGp0ZXJqc215a3N6cnlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODc4MDUsImV4cCI6MjA1ODY2MzgwNX0.RBOCjjRq7uQhliOZ49sEEf_8gLFz3RopkU1oISGdkCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);